/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void start_button(GButton source, GEvent event) { //_CODE_:startButton:312855:
  startButton.setVisible(false);
  reset();
} //_CODE_:startButton:312855:

public void pause_clicked(GButton source, GEvent event) { //_CODE_:pauseButton:653910:
  pause = true;
  pauseButton.setVisible(false);
  playButton.setVisible(true);
} //_CODE_:pauseButton:653910:

public void play_clicked(GButton source, GEvent event) { //_CODE_:playButton:389387:
  pause = false;
  playButton.setVisible(false);
  pauseButton.setVisible(true);
} //_CODE_:playButton:389387:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  startButton = new GButton(this, 350, 350, 100, 50);
  startButton.setText("Start");
  startButton.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  startButton.addEventHandler(this, "start_button");
  pauseButton = new GButton(this, 26, 20, 100, 50);
  pauseButton.setText("Pause");
  pauseButton.setLocalColorScheme(GCScheme.RED_SCHEME);
  pauseButton.addEventHandler(this, "pause_clicked");
  playButton = new GButton(this, 26, 20, 100, 50);
  playButton.setText("Play");
  playButton.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  playButton.addEventHandler(this, "play_clicked");
}

// Variable declarations 
// autogenerated do not edit
GButton startButton; 
GButton pauseButton; 
GButton playButton; 
